# Generated by Django 2.2.7 on 2019-11-15 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(default='', help_text='Unique namespace ID. Configurable via the SMARTMODELS_OWNER_PK_FIELD setting.', max_length=100, unique=True, verbose_name='Namespace ID')),
                ('users', models.ManyToManyField(help_text='Contributors (users) to this org, department, etc.', related_name='namespaces_liable_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'SMARTMODELS_NAMESPACE_MODEL',
            },
        ),
    ]
