# Generated by Django 2.2.7 on 2019-11-20 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='users',
            field=models.ManyToManyField(help_text='Contributors (users) to this org, department, etc.', related_name='namespaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
