# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-30 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'sentinel', help_text='The Primary Key field. Configurable via the SMART_MODELS_OWNER_PK_FIELD setting.', max_length=255, unique=True, verbose_name='Owner ID')),
                ('users', models.ManyToManyField(help_text='Contributors (users) to this org, department, etc.', related_name='namespaces_liable_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'SMART_MODELS_OWNER_MODEL',
            },
        ),
    ]
