# Generated by Django 2.2.7 on 2019-11-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartmodels.models.smart


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.SMARTMODELS_NAMESPACE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('activity_type', models.CharField(choices=[('F', 'Favorite'), ('L', 'Like'), ('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator (owner) of the resource.', null=True, on_delete=models.SET(smartmodels.models.smart.get_sentinel_user), related_name='activitys_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(smartmodels.models.smart.get_sentinel_user), related_name='activitys_deleted', to=settings.AUTH_USER_MODEL)),
                ('namespaces', models.ManyToManyField(help_text='Visibility domain: org, district, domain, etc.', related_name='activitys_owned', to=settings.SMARTMODELS_NAMESPACE_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User obo. whom this resource is created. The sentinel owner on deletion.', null=True, on_delete=models.SET(smartmodels.models.smart.get_sentinel_user), related_name='activitys', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(smartmodels.models.smart.get_sentinel_user), related_name='activitys_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
